name: Application CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  app-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - name: CI
        run: |
          npm ci
          npm run check

  app-deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [app-ci]
    runs-on: ubuntu-latest
    steps:
      - name: Auto Deploy to Trunk
        uses: octokit/request-action@v2.x
        with:
          route: POST /repos/${{ github.repository}}/deployments
          task: 'deploy:github'
          ref: ${{ github.ref }}
          required_context: '[]'
          environment: 'trunk'
          auto_merge: false
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
