name: Application Deploy

on:
  - deployment

jobs:
  deploy-to-s3:
    if: github.event.deployment.task == 'deploy:github'
    runs-on: ubuntu-latest
    environment: ${{ github.event.deployment.environment }}
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE }}
          aws-region: ap-southeast-1

      - name: Setup NodeJs
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Deploy to S3
        run: aws s3 sync dist/ s3://${{ vars.AWS_BUCKET_NAME }}
